### ISSUE TITLE
waveform not displayed when audio is single channel mono

### ISSUE THREAD

**Issue by duck7000** [maxrd2/subtitlecomposer#105] opened 2018-08-17 18:24 UTC
If i want to edit a subtitle associated with a video file witch contains a single channel mono audio track then the waveform is not displayed

I this a problem/bug? or has it to do with the OS (in my case Linux mint cinnamon18.3)?

I'll admit that this is rarely a issue but it has happened a few times

**Comment by maxrd2** [comment] 2018-10-17 11:03
I can't reproduce it here, it decodes and display single channel normally.
Can you paste the output of :
```
ffmpeg -i non-working-video.file
```
Maybe the audio in the file is broken?

**Comment by duck7000** [comment] 2018-10-17 14:11
Thanks for the reply and testing!

Well i searched but can't find the video file anymore..sorry. I tested with another single audio mono video file and it works like it should. So there must have been something wrong with the video file i used.

It rarely happens so best i close this issue for now, but if it happens again i will save the file and the subtitle and open a new issue.

And thanks for creating this excellent subtitle editor, i use it almost every day!

**Comment by duck7000** [comment] 2018-12-11 16:30
Well i finaly found a movie, but it is not mono.. so it happens with others too.

Here is the output from ffmpeg:

```
> ffmpeg -i They.Live.1988.Blu-ray.DTS-HD-PCM.mkv
> ffmpeg version 3.4.2-1~16.04.york0.2 Copyright (c) 2000-2018 the FFmpeg developers
>   built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.9) 20160609
>   configuration: --prefix=/usr --extra-version='1~16.04.york0.2' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
>   WARNING: library configuration mismatch
>   avcodec     configuration: --prefix=/usr --extra-version='1~16.04.york0.2' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared --enable-version3 --disable-doc --disable-programs --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libtesseract --enable-libvo_amrwbenc
>   libavutil      55. 78.100 / 55. 78.100
>   libavcodec     57.107.100 / 57.107.100
>   libavformat    57. 83.100 / 57. 83.100
>   libavdevice    57. 10.100 / 57. 10.100
>   libavfilter     6.107.100 /  6.107.100
>   libavresample   3.  7.  0 /  3.  7.  0
>   libswscale      4.  8.100 /  4.  8.100
>   libswresample   2.  9.100 /  2.  9.100
>   libpostproc    54.  7.100 / 54.  7.100
> [matroska,webm @ 0x557ba0f5eee0] Could not find codec parameters for stream 3 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
> Consider increasing the value for the 'analyzeduration' and 'probesize' options
> Guessed Channel Layout for Input Stream #0.1 : stereo
> Input #0, matroska,webm, from 'They.Live.1988.Blu-ray.DTS-HD-PCM.mkv':
>   Metadata:
>     encoder         : libebml v1.3.6 + libmatroska v1.4.9
>     creation_time   : 2018-12-11T12:20:43.000000Z
>   Duration: 01:34:27.00, start: 0.000000, bitrate: 28416 kb/s
>     Stream #0:0: Video: h264 (High), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 24 fps, 24 tbr, 1k tbn, 48 tbc (default)
>     Metadata:
>       BPS-eng         : 21856899
>       DURATION-eng    : 01:34:17.834000000
>       NUMBER_OF_FRAMES-eng: 135788
>       NUMBER_OF_BYTES-eng: 15457838355
>       _STATISTICS_WRITING_APP-eng: mkvmerge v29.0.0 ('Like It Or Not') 64-bit
>       _STATISTICS_WRITING_DATE_UTC-eng: 2018-12-11 12:20:43
>       _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
>     Stream #0:1(eng): Audio: pcm_s24le, 48000 Hz, stereo, s32 (24 bit), 2304 kb/s (default)
>     Metadata:
>       BPS-eng         : 2304000
>       DURATION-eng    : 01:34:27.000000000
>       NUMBER_OF_FRAMES-eng: 1133400
>       NUMBER_OF_BYTES-eng: 1632096000
>       _STATISTICS_WRITING_APP-eng: mkvmerge v29.0.0 ('Like It Or Not') 64-bit
>       _STATISTICS_WRITING_DATE_UTC-eng: 2018-12-11 12:20:43
>       _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
>     Stream #0:2(eng): Audio: dts (DTS-HD MA), 48000 Hz, 5.1(side), s32p (24 bit)
>     Metadata:
>       BPS-eng         : 4277190
>       DURATION-eng    : 01:34:26.998000000
>       NUMBER_OF_FRAMES-eng: 531281
>       NUMBER_OF_BYTES-eng: 3029853884
>       _STATISTICS_WRITING_APP-eng: mkvmerge v29.0.0 ('Like It Or Not') 64-bit
>       _STATISTICS_WRITING_DATE_UTC-eng: 2018-12-11 12:20:43
>       _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
>     Stream #0:3(eng): Subtitle: hdmv_pgs_subtitle
>     Metadata:
>       BPS-eng         : 19416
>       DURATION-eng    : 01:30:10.417000000
>       NUMBER_OF_FRAMES-eng: 1584
>       NUMBER_OF_BYTES-eng: 13131751
>       _STATISTICS_WRITING_APP-eng: mkvmerge v29.0.0 ('Like It Or Not') 64-bit
>       _STATISTICS_WRITING_DATE_UTC-eng: 2018-12-11 12:20:43
>       _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
> At least one output file must be specified
```
To be honest i still use the 0.5.6 version that @muzena made a while back on linuxmint 18.3
I can test it though on linuxmint 19 with the latest git version if that is necessary?

**Comment by duck7000** [comment] 2018-12-11 19:03
I tried it on linuxmint 19, latest git version and it is the same.
No waveform displayed

**Comment by maxrd2** [comment] 2018-12-12 15:43
Thanks for more info here, won't be able to fix this before i manage to reproduce it with some video file. It might take awhile :-/

**Comment by duck7000** [comment] 2018-12-12 16:08
I understand that, thanks for looking in to this!

**Comment by duck7000** [comment] 2019-06-11 10:30
I found another movie file that didn't produce a waveform.
It appears to be only happening with pcm audio though.

ffmpeg -i Graveyard.Shift.1990.BluRay.NL.mkv
ffmpeg version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
  configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared --enable-version3 --disable-doc --disable-programs --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libtesseract --enable-libvo_amrwbenc
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Guessed Channel Layout for Input Stream #0.1 : stereo
Input #0, matroska,webm, from 'Graveyard.Shift.1990.BluRay.NL.mkv':
  Metadata:
    encoder         : libmakemkv v1.14.3 (1.3.5/1.4.7) x86_64-linux-gnu
    creation_time   : 2019-06-11T09:32:07.000000Z
  Duration: 01:25:52.69, start: 0.000000, bitrate: 30576 kb/s
    Chapter #0:0: start 0.000000, end 1014.179833
    Metadata:
      title           : Chapter 01
    Chapter #0:1: start 1014.179833, end 1774.898125
    Metadata:
      title           : Chapter 02
    Chapter #0:2: start 1774.898125, end 2629.418458
    Metadata:
      title           : Chapter 03
    Chapter #0:3: start 2629.418458, end 3377.123750
    Metadata:
      title           : Chapter 04
    Chapter #0:4: start 3377.123750, end 3854.267083
    Metadata:
      title           : Chapter 05
    Chapter #0:5: start 3854.267083, end 4188.475958
    Metadata:
      title           : Chapter 06
    Chapter #0:6: start 4188.475958, end 4644.931958
    Metadata:
      title           : Chapter 07
    Chapter #0:7: start 4644.931958, end 5152.689208
    Metadata:
      title           : Chapter 08
    Stream #0:0(eng): Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc
    Metadata:
      BPS-eng         : 29023701
      DURATION-eng    : 01:25:52.689208333
      NUMBER_OF_FRAMES-eng: 123541
      NUMBER_OF_BYTES-eng: 18693763189
      SOURCE_ID-eng   : 001011
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.14.3 linux(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2019-06-11 09:32:07
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
    Stream #0:1(eng): Audio: pcm_s16le, 48000 Hz, stereo, s16, 1536 kb/s (default)
    Metadata:
      title           : Stereo
      BPS-eng         : 1536000
      DURATION-eng    : 01:25:52.025000000
      NUMBER_OF_FRAMES-eng: 154561
      NUMBER_OF_BYTES-eng: 989188800
      SOURCE_ID-eng   : 001101
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.14.3 linux(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2019-06-11 09:32:07
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
    Stream #0:2(eng): Subtitle: hdmv_pgs_subtitle, 1920x1080 (default)
    Metadata:
      BPS-eng         : 14179
      DURATION-eng    : 01:20:49.532187500
      NUMBER_OF_FRAMES-eng: 1179
      NUMBER_OF_BYTES-eng: 8595677
      SOURCE_ID-eng   : 001202
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.14.3 linux(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2019-06-11 09:32:07
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID

It is just to inform you

**Comment by maxrd2** [comment] 2019-06-11 13:05
thanks... will try to test it on video with pcm audio.

**Comment by maxrd2** [comment] 2019-06-11 14:19
Please confirm this is fixed now.

**Comment by duck7000** [comment] 2019-06-11 14:26
Thanks for the fix!

I'm trying to build a deb installer right now
i'll use checkinstall on my linux mint system, if it all works maybe @muzena can build a real deb installer? He maintains the git repo afaik

**Comment by duck7000** [comment] 2019-06-11 14:37
As far as tested the video doesn't play anymore, other video's also not anymore.
So i can't see if it works or not

**Comment by duck7000** [comment] 2019-06-11 15:13
after further testing it appears that auto loading video when opening a subtitle doesn't work anymore with this patch?
If i open the video manually the waveform does work with pcm audio! so the fix works!

**Comment by maxrd2** [comment] 2019-06-11 15:31
Auto loading of video is a setting in preferences, and some defaults have been changed some time ago.
This patch changed completely unrelated code.
Will close the ticket now. Feel free to reopen if you still see some issues.
Thank you for report.

**Closed by maxrd2** 2019-06-11 15:31 UTC
Labels: bug

**Comment by duck7000** [comment] 2019-06-11 15:44
I know that auto loading is a setting in preferences, it is checked and works with all other videos.
Since this patch auto loading  of videos with pcm audio does not work anymore.

So i don't know what happened but it feels related.
The released appimage has the same behavior, although i don't know if it did work with previous versions, never used it before.
