### ISSUE TITLE
Subtitlecomposer crash

### ISSUE THREAD

**Issue by muzena** [maxrd2/subtitlecomposer#59] opened 2016-05-08 14:17 UTC
What is purpose of main bar -> Video -> Close Video options is this same as stop video button?
When I Close Video then I try reopen video, subtitlecomposer is crash.

**Comment by Martchus** [comment] 2016-05-08 17:39
After pressing the stop button you can press the play button to start again. When closing the video, you need to reopen the video first.

I can't reproduce the issue with any video backend. Which video backends did you try? Can you provide debug information?

**Comment by muzena** [comment] 2016-05-08 18:40
@Martchus 
On Ubuntu unity xenial works, on Linux mint 18 unstable I get this error in terminal:
[MPV: cplayer ]  info :  

[MPV: cplayer ]  info :  Playing: /mnt/MEDIJA/FILMOVI/FILM/FILM/Star Trek ALL Movies/Star.Trek.VII.Generations.1994.EUR.BluRay.1080p.AVC.TrueHD.5.1.REMUX-FraMeSToR/Star.Trek.VII.Generations.1994.EUR.BluRay.1080p.AVC.TrueHD.5.1.REMUX-FraMeSToR.mkv

[MPV: cplayer ]  info :   (+) Video --vid=1 (*) (h264)

[MPV: cplayer ]  info :   (+) Audio --aid=1 --alang=eng (*) (truehd)

[MPV: cplayer ]  info :       Audio --aid=2 --alang=eng 'English Directors Commentary 1' (ac3)

[MPV: cplayer ]  info :       Audio --aid=3 --alang=eng 'English Directors Commentary 2' (ac3)

[MPV: cplayer ]  info :       Subs  --sid=1 --slang=ara (hdmv_pgs_subtitle)

[MPV: cplayer ]  info :       Subs  --sid=2 --slang=dan (hdmv_pgs_subtitle)

[MPV: cplayer ]  info :       Subs  --sid=3 --slang=ger (hdmv_pgs_subtitle)

[MPV: cplayer ]  info :       Subs  --sid=4 --slang=eng (hdmv_pgs_subtitle)

[MPV: cplayer ]  info :       Subs  --sid=5 --slang=spa (hdmv_pgs_subtitle)

[MPV: cplayer ]  info :       Subs  --sid=6 --slang=fre (*) (hdmv_pgs_subtitle)

[MPV: cplayer ]  info :       Subs  --sid=7 --slang=hrv (hdmv_pgs_subtitle)

[MPV: cplayer ]  info :       Subs  --sid=8 --slang=ita (hdmv_pgs_subtitle)

[MPV: cplayer ]  info :       Subs  --sid=9 --slang=dut (hdmv_pgs_subtitle)

[MPV: cplayer ]  info :       Subs  --sid=10 --slang=nor (hdmv_pgs_subtitle)

[MPV: cplayer ]  info :       Subs  --sid=11 --slang=por (hdmv_pgs_subtitle)

[MPV: cplayer ]  info :       Subs  --sid=12 --slang=fin (hdmv_pgs_subtitle)

[MPV: cplayer ]  info :       Subs  --sid=13 --slang=swe (hdmv_pgs_subtitle)

[MPV: cplayer ]  info :       Subs  --sid=14 --slang=eng (hdmv_pgs_subtitle)

[MPV: cplayer ]  info :       Subs  --sid=15 --slang=ger (hdmv_pgs_subtitle)

[MPV: cplayer ]  info :       Subs  --sid=16 --slang=eng (hdmv_pgs_subtitle)

[MPV: cplayer ]  info :       Subs  --sid=17 --slang=spa (hdmv_pgs_subtitle)

[MPV: cplayer ]  info :       Subs  --sid=18 (hdmv_pgs_subtitle)

[MPV: cplayer ]  info :       Subs  --sid=19 --slang=ita (hdmv_pgs_subtitle)

[MPV: cplayer ]  info :       Subs  --sid=20 --slang=ger (hdmv_pgs_subtitle)

[MPV: cplayer ]  info :       Subs  --sid=21 --slang=eng (hdmv_pgs_subtitle)

[MPV: cplayer ]  info :       Subs  --sid=22 --slang=spa (hdmv_pgs_subtitle)

[MPV: cplayer ]  info :       Subs  --sid=23 --slang=fre (hdmv_pgs_subtitle)

[MPV: cplayer ]  info :       Subs  --sid=24 --slang=ita (hdmv_pgs_subtitle)

[MPV: cplayer ]  info :       Subs  --sid=25 --slang=ger (hdmv_pgs_subtitle)

[MPV: cplayer ]  info :       Subs  --sid=26 --slang=spa (hdmv_pgs_subtitle)

[MPV: cplayer ]  info :       Subs  --sid=27 --slang=fre (hdmv_pgs_subtitle)

[MPV: cplayer ]  info :       Subs  --sid=28 --slang=ita (hdmv_pgs_subtitle)

[MPV: cplayer ]  info :       Subs  --sid=29 --slang=chi (hdmv_pgs_subtitle)

[MPV: cplayer ]  info :       Subs  --sid=30 --slang=chi (hdmv_pgs_subtitle)

Generated caps:  audio/x-raw, format=(string)U8, width=(int)8, depth=(int)8, signed=(boolean)false, rate=(int)8000
[MPV: vo/vdpau/x11 ]  warn :  Disabling screensaver failed (4). Make sure the xdg-screensaver script is installed.

[MPV: cplayer ]  info :  AO: [alsa] 48000Hz stereo 2ch s32


ERROR: Caught a segmentation fault while loading plugin file:
/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstlibav.so

Please either:
- remove it and restart.
- run with --gst-disable-segtrap --gst-disable-registry-fork and debug.
QObject::~QObject: Timers cannot be stopped from another thread
QSocketNotifier: Invalid socket 16 and type 'Read', disabling...
QObject::killTimer: Timers cannot be stopped from another thread
QObject::~QObject: Timers cannot be stopped from another thread
Segmentacijska greška
[error.log.zip](https://github.com/maxrd2/subtitlecomposer/files/254049/error.log.zip)

**Comment by Martchus** [comment] 2016-05-08 19:04
So you are using the MPlayer backend. Are other backends affected, too?

I don't use Mint or Ubuntu, so I don't know what could make the difference.

**Comment by muzena** [comment] 2016-05-08 20:10
No mpv, mplayer but only when I have enabled vdpau hardware decoding.

**Comment by Martchus** [comment] 2016-05-08 20:26
Yes, the log shows clearly you're using MPV. I just confused it with MPlayer when writing the comment.

It works for me with vdpau enabled, too. However, if the use of hardware decoding affects the issue, it might be useful to know which graphic card and which driver (version) you use.

But vdpau works in general? No problems when using MPV directly? What about the other backends?

By the way, I'm using NVIDIA GTX 560 Ti with proprietary NVIDIA driver (364.19).

**Comment by muzena** [comment] 2016-05-08 21:38
ATi Radeon HD 5670 open source radeon driver and mesa-vdpau-drivers package for video decoding

**Comment by maxrd2** [comment] 2016-05-09 09:48
I can't reproduce this either.
Can you please tell me which version of subtitlecomposer you are using?
Can you please start the application from terminal like this:
```
gdb subtitlecomposer
(gdb) run
.... reproduce steps to crash ...
(gdb) bt
```
and then attach output of everything.

**Comment by muzena** [comment] 2016-05-09 13:43
Last version from github.

[gdboutput.zip](https://github.com/maxrd2/subtitlecomposer/files/255085/gdboutput.zip)

**Comment by maxrd2** [comment] 2016-05-09 17:16
Stacktrace doesn't show any subtitlecomposer calls, it seems to be crashing in some thread created by gstreamer. It might be a bug in some codec inside gstreamer (have noticed that video player is complaining about corrupted audio stream).
If you can install debug symbols for gstreamer stacktrace output would be more detailed.
Does the same crash/problem happen with every video file?
Do you get crash in some gstreamer videoplayer like totem, if you open that video, then close it (without closing the app) and reopen it?

**Comment by muzena** [comment] 2016-05-10 16:36
@maxrd2 
I now try on ubuntu 16.04 Xenial and it works.
I think that problem is in my frankenstein distro, I've install Ubuntu 16.04 minimal.iso and manually add Linux Mint 18 Sarah repositories and install Cinnamon desktop nemo and other packages manually maybe some packages cause this conflict, or some package missing, next month releases Linux Mint 18 Cinnamon beta then i will reinstall system and try Subtitlecomposer again to see if error still happens.

**Comment by maxrd2** [comment] 2016-05-10 17:44
ok thanks.. will close it for time being

**Closed by maxrd2** 2016-05-10 17:44 UTC
