### ISSUE TITLE
Building subtitlecomposer - Policy "CMP0063" is not known to this version of CMake.

### ISSUE THREAD

**Issue by muzena** [maxrd2/subtitlecomposer#38] opened 2016-03-23 12:53 UTC
@maxrd2 
Pokušavam ručno instalirat Subtitlecomposer, ne radi.
naredba ./configure i cmake .. ne rade daju greške, mislim da ne radi u kd5 jel stoje unutra od kde4 podešavanja.
Jel možeš to popravit ili upute za ručnu podešavanje i kompilaciju dati.
To sam pokušavao na kubuntu 16.04 kompajlirat.

**Comment by maxrd2** [comment] 2016-03-23 14:02
Please write in english.
Have updated ./configure and ./install scripts, you should be able to build and install by running:
```
./configure && cd build && make && sudo make install
```
or just:
```
./install
```
Please note that KDE Frameworks 5 is required for current version. If you want to build old KDE4 version you should checkout kde4 branch:
```
git clone https://github.com/maxrd2/subtitlecomposer.git subtitlecomposer
cd subtitlecomposer
git checkout kde4
./install
```

**Comment by muzena** [comment] 2016-03-23 15:26
I've install all dependencies, run ./configure, same error again.
Here is CMakeOutput.log:

[CMakeOutput.log.zip](https://github.com/maxrd2/subtitlecomposer/files/186278/CMakeOutput.log.zip)

**Comment by maxrd2** [comment] 2016-03-23 23:26
I can't see nothing from CMakeOutput.log you've attached.
```
./configure 2>&1 | gzip >configure.output.gz
```
Can you please attach configure.output.gz after running the above command?

**Comment by muzena** [comment] 2016-03-24 06:38
@maxrd2 
Configure file:
[configure.output.gz](https://github.com/maxrd2/subtitlecomposer/files/187346/configure.output.gz)

**Comment by maxrd2** [comment] 2016-03-24 09:56
https://cmake.org/cmake/help/v3.3/policy/CMP0063.html

**Comment by muzena** [comment] 2016-03-25 11:21
@maxrd2 
In Configurations > VideoPlayer - There is no Decoder backend: and Subtitlecomposer only work with selected VideoPlayer: MPlayer  but only when is selected manually in configuration MPlayer > Executable path: /usr/bin/mplayer
And there is no phonon in Configurations.
Install log:
[install.output.txt](https://github.com/maxrd2/subtitlecomposer/files/189417/install.output.txt)
Screenshot:



![si5k60 q](https://cloud.githubusercontent.com/assets/1978777/14043320/3f9c03b4-f283-11e5-80c0-88b8a08de7d7.PNG)

**Comment by maxrd2** [comment] 2016-03-25 13:04
Decoder backend wasn't ever used for anything so you can just ignore that. Will remove it soon from settings.

Phonon doesn't have it's configuration tab in settings. If it's missing from "VideoPlayer backend" select menu, it probably means that plugin failed to load because of some missing dependency.
If that's the case please try running following and see if it says that some .so cannot be found:
```
ldd /usr/lib/subtitlecomposer/phononplayer.so
```

Have noticed on that screenshot that all of stock icons are missing. Is your KDE/Plasma5 installation ok? Are other Plasma applications displaying icons correctly?

**Comment by muzena** [comment] 2016-03-25 19:00
@maxrd2 
phononplayer.so log:
[phononplayer.so.output.txt](https://github.com/maxrd2/subtitlecomposer/files/189918/phononplayer.so.output.txt)
Icons missing probably because I'm using Cinnamon. In plasma icons are visible.

**Comment by maxrd2** [comment] 2016-03-25 20:22
I'm not sure anymore... What exactly is a problem with your build/installation?

Have just tried building on fresh install of Kubuntu 16.04. It builds and works/looks fine here.

Have installed build dependencies:
```
sudo apt install \
    build-dep qtbase5-dev git cmake extra-cmake-modules \
    libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
    kdelibs5-dev libkf5xmlgui-dev kross-dev \
    mpv libmpv-dev mplayer libxine2-dev \
    libphonon4qt5-dev libphonon4qt5experimental-dev
```

Then got sources:
```
git clone https://github.com/maxrd2/subtitlecomposer.git
```

And then build:
```
cd subtitlecomposer
./configure
cd build
make
sudo make install
```

**Comment by muzena** [comment] 2016-03-26 16:23
Now it works.
Only there is problem with video preview.
In Plasama video preview work.
In Unity work but when put video preview in fullscreen and go back in app preview, in app preview is black, no picture.
In Cinnamon also work but when put video preview in fullscreen and go back in app preview, video preview continue in his own window outside subtitlecomposer app.
![slika zaslona](https://cloud.githubusercontent.com/assets/1978777/14061091/5b73ed3c-f377-11e5-90f6-8d38de3a924e.png)

**Comment by maxrd2** [comment] 2016-03-26 16:43
Which video player backend is that? Mplayer?

**Comment by muzena** [comment] 2016-03-26 16:44
I try it with all player backend, the same issue, but this is MPV

**Comment by maxrd2** [comment] 2016-03-26 16:45
Thanks.. will try to reproduce it and fix it.

**Comment by Martchus** [comment] 2016-03-26 17:38
I can reproduce the issues with cinnamon:
1. Video player is outside the main window after escaping full screen. It doesn't matter which backend is used.
2. The icons in the settings dialog aren't shown. I use the same icon theme as under Plasma, so missing icons can not be the cause. Other Qt 5 applications (eg. the Tag Editor application I've written) show icons correctly.

I'll try to investigate this further and do tests in a plain Open Box session as well.

**Comment by Martchus** [comment] 2016-03-26 18:23
I see the problem about the missing icons. Subtitle Composer currently loads the icons in a way which is only possible when using the KDE icon engine. I didn't even know that this way of locating icons exists. However, I'd propose to switch to a more generic approach.

**Comment by maxrd2** [comment] 2016-03-27 13:17
@muzena Please try if you can see icons properly now. Martchus also submitted patch #41 for fullscreen issue and should be working fine now.

**Comment by muzena** [comment] 2016-03-27 20:08
@maxrd2 
Now it's all ok.
Video preview is not black and is in apps window after exiting fullscreen, and icons is shown properly.
But not all translations is available, some string is missing eg. Video sink, Audio sink... this string are been available in old version.

**Comment by Martchus** [comment] 2016-03-27 22:00
If the strings have been changed (even when the changes are only slight) they must be retranslated. Unfortunately I can't help with this because I don't speak your language.

If you like to contribute, you need to regenerate the translation files first:
`updated *.po files using ./po/Messages.sh`
Then you can do the changes with Poedit or a similar tool. Qt Linguist didn't work well for me because it was not able find the relevant sources.
Unfortunately Subtitle Composer always tries to load the system version of the translations which makes testing very hard.

**Comment by maxrd2** [comment] 2016-03-28 08:24
@muzena Like @Martchus said... you should launch ./po/Messages.sh to update translation files from sources. That way you can be sure that .po files are using latest translation strings.

**Comment by muzena** [comment] 2016-03-28 08:35
@maxrd2  @Martchus 
This missing strings are marked as fuzzy in *.po files.

**Comment by maxrd2** [comment] 2016-03-28 08:37
Fuzzy strings are automatically detected translations.
They should just be checked for correctness, and fuzzy flag should be removed.
Poedit has a button somewhere to unflag translation as fuzzy.

**Comment by muzena** [comment] 2016-03-28 08:43
@maxrd2 
Not fuzzy, I meant wrong.
I think they marked as obsolete not fuzzy.

![screenshot from 2016-03-28 10 42 50](https://cloud.githubusercontent.com/assets/1978777/14074521/e4b3311a-f4d1-11e5-918c-8884d101fe46.png)

**Comment by maxrd2** [comment] 2016-03-28 09:08
Those texts were removed... as were used by old decoder backend code which didn't do anything at all.
You should be good to delete those or just leave them as reference.
Thanks for your help.
Will close this one now.

**Closed by maxrd2** 2016-03-28 09:08 UTC
Labels: question

**Comment by muzena** [comment] 2016-03-30 16:29
@maxrd2 
When I install PocketSphinx dependencies I was unable to compile subtitlecomposer.

[make.log.zip](https://github.com/maxrd2/subtitlecomposer/files/195963/make.log.zip)

**Comment by maxrd2** [comment] 2016-03-30 22:29
have moved this to issue #45
