### ISSUE TITLE
Font size not working qt5ct

### ISSUE THREAD

**Issue by duck7000** [maxrd2/subtitlecomposer#126] opened 2019-05-18 19:58 UTC
If i set the font size in qt5ct tool, all fonts are affected except for the subtitle text?

![Screenshot from 2019-05-18 21-44-16](https://user-images.githubusercontent.com/15360048/57974350-12a09280-79b7-11e9-90bb-5940be26c918.png)
Here is a screenshot, i set the font to 11, all are 11 except the subtitle text.

The second problem is that the subtitle text not is vertically centered?

This is not theme related ( i tried breeze and gtk2) it is the same in both.
I tested this on linuxmint and kdeneon, behaviour is the same.

What is the solution to this problem?

**Comment by duck7000** [comment] 2019-06-09 15:38
Apparently i'm the only one who notice this problem?
Nobody has a clue how to fix this?

**Comment by Martchus** [comment] 2019-06-09 16:25
I can only reproduce that the vertical alignment is a bit off. That is even notable when the font size matches of the subtitle text matches the font size of the other columns.

However, I could not reproduce that the font size set via qt5ct is ignored. I also set it to Noto Sans 11 and the subtitle text is rendered in that size.

I've tested using the current versions:  
```
pacman -Q subtitlecomposer qt5ct qt5-base 
subtitlecomposer 0.6.6-6
qt5ct 0.39-1
qt5-base 5.12.3-2
```

**Comment by duck7000** [comment] 2019-06-09 20:07
@Martchus 
Thanks for your reaction

So on your system (arch linux i believe?) All the text in the above image is the same?
The point is that on my linuxmint 19.1 all text is changed to noto sans 11 except the column with the subtitle text.
Weird problem, could be a Ubuntu base problem then?
i use the latest git version:
https://code.launchpad.net/~subtitlecomposer/+archive/ubuntu/subtitlecomposer-git

What distro do you use?

I also can use the version in the linuxmint repo (i believe that is the latest 0.6.6 release) and check if that makes a different

**Comment by Martchus** [comment] 2019-06-09 21:36
> All the text in the above image is the same?

Yes. And I'm using Arch Linux and tested with the Breeze Qt Widgets theme (via qt5ct).

Maybe it is a bug which has been introduced after the latest release. Likely just a hard-coded font size which would be easy to fix.

**Comment by duck7000** [comment] 2019-06-10 08:05
Thanks for testing this issue

I removed the git version and used the repo version (0.6.6) but the issue is the same.

Maybe you are right about hard-coded font size, it certainly looks like that.

I will try Manjaro, the issue shouldn't be there like you said. In that case the issue  could be caused by ubuntu base? maybe older versions of qt5 libs?

**Comment by duck7000** [comment] 2019-06-10 09:31
I tested it on Manjaro and at first you are right that this issue does not occur.

However if you us qt5ct tool to use much larger or smaller fonts the issue does occur!
See screenshots, the first is with font noto sans 14, the second with noto sans 9
![screenshot noto 14](https://user-images.githubusercontent.com/15360048/59186339-e40b7700-8b72-11e9-9e72-7e40e426e5f3.png)
![Screenshot noto 9](https://user-images.githubusercontent.com/15360048/59186343-e7066780-8b72-11e9-8c65-6b7fb572f8ca.png)
So i think you are right about hard coded font for the subtitle text column?

**Comment by duck7000** [comment] 2019-06-11 08:50
I tested it with the git version as well (0.7.0) but the issue is still the same

**Comment by maxrd2** [comment] 2019-06-11 09:34
Subtitle text is rendered through rich text edit. Have you tried restarting subtitle composer after changing the font size? It works for me.

**Comment by duck7000** [comment] 2019-06-11 10:15
@maxrd2 
yes i restarted subtitlecomposer after the font change, still the same.

Really strange that neither of you can reproduce this issue, while my screenshots tell a different story.
This behavior is the same on all systems i tested, even on manjaro, (while at first it seems to work), with the font size at 11 the subtitle column is still smaller than the rest.

I noticed one time that at first the fonts where set to for example 14, but after a few seconds the font switched back to i believe system font size?

In the last 2 screenshots the text column behavior is strange, it looks like it does the opposite of the font setting? Can either of you reproduce this behavior?

@Martchus 
did you compile this version yourself: subtitlecomposer 0.6.6-6?
in the AUR there is the git version (0.7.0) or 0.6.6-3

In the linuxmint repo there is 0.6.6, and the git ppa version 0.7.0

The issue is there in all versions i tested on all systems, so i don't understand why it works on your systems?

**Comment by maxrd2** [comment] 2019-06-11 10:41
Have pushed a patch that will vertically center text. Text was also being wrapped into a paragraph block.
Maybe your theme forces font size on paragraph block, or something similar. Please try with latest changes.

**Comment by duck7000** [comment] 2019-06-11 13:24
Thanks for the patch, although i'm not sure i will be able to compile it on my system, it has given me a lot of trouble in the past to make it work on Linuxmint so i kindly ask @muzena if he can make a deb version with this patch?
Or anyone else of course

**Comment by maxrd2** [comment] 2019-06-11 14:34
@duck7000 You can always download Subtitle_Composer-x86_64.AppImage from [releases page](https://github.com/maxrd2/subtitlecomposer/releases)

**Comment by duck7000** [comment] 2019-06-11 14:38
I managed to compile it.
The good news is dat de subtitle text is now centered.
The bad news is that the issue is still the same

**Comment by duck7000** [comment] 2019-06-11 15:16
Thanks for your suggestion to use the appimage.

This works but how do i set the icons and fonts?
Appimage doesn't seem to use settings from qt5ct tool?

**Comment by maxrd2** [comment] 2019-06-11 15:33
AppImage ships with default breeze theme and icons. Don't think you can change it easily.

**Comment by Martchus** [comment] 2019-06-11 15:48
And I suppose the AppImage ships its own Qt libraries and plugins. It is not generally possible to combine that the system provided plugins such as the qt5ct platform integration plugin.

**Comment by duck7000** [comment] 2019-06-11 16:04
Okay i understand, so your basically saying that all my tests on different systems is all to blame to theme or style related?
kdeneon, standard install, nothing changed other than subtitlecomposer, results in this issue.
Manjaro xfce 18.04, standard install, nothing changed other than subtitlecomposer, results in this issue.
Linuxmint cinnamon 19.1, results in this issue.

But on your Arch linux it all works like it should, i don't understand why? Manjaro is based on Arch linux so why don't you have this issue?

What can i change in the style or theme to make this issue go away?
When i set the font size system wide all applications will be that big, while i only need this app to be a little bigger.
Using the appimage doesn't change anything, makes it worse, because i can't change icons or font size.

In SC i also can set font sizes but only for the video and waveform, not the subtitle text.

Sorry, i get a little frustrated about this..

**Comment by maxrd2** [comment] 2019-06-11 17:56
@duck7000 What I'm saying is that i BELIEVE that something else is to blame... I might be wrong, but don't think I am.
The reason that I believe so is because SubtitleComposer is using QTextDocument to render subtitle html inside QTreeView (which lists all subtitle lines). Code isn't forcing any font face nor size there.

Since subtitle text is html that is being rendered, I GUESS that some style author for some theme somewhere have used absolute unit for default font size instead of relative one and font size doesn't increase when you change it in preferences.

I could investigate more if I could reproduce this problem on my machine, but I can't.. it works here with default breeze theme. If I manage to reproduce it at some point I will be able to help more. Right now it can only be guessing game from my side.

**Comment by maxrd2** [comment] 2019-06-11 19:27
Have made a change that will force default font onto subtitle text. It also detects the change in system font configuration and should update the font when detected. If that doesn't help you should try asking on issue tracker of whatever theme you are using.

**Comment by duck7000** [comment] 2019-06-11 21:57
Thanks for your explanation
It was not meant to rant, and i understand that this issue might been a theme/style problem.
Although i did try different themes, including breeze, on different platforms, which means they all have the same problem..

Well if you can't reproduce there is no point to take it any further.

Thank you for your investigating.

**Comment by maxrd2** [comment] 2019-06-12 08:15
Please try the change I did in last commit... I think that should help.

**Comment by duck7000** [comment] 2019-06-12 10:39
Oke i will compile it and hope that it will help.

Thanks for trying to fix this!

**Comment by duck7000** [comment] 2019-06-12 10:55
@maxrd2 
Your fix is working!!
![Screenshot from 2019-06-12 12-49-59](https://user-images.githubusercontent.com/15360048/59345591-b825f800-8d10-11e9-9441-f11437a67751.png)

Font size 11 is working for all columns now!
Thank you very much for the fix and your patience.

**Comment by maxrd2** [comment] 2019-06-12 13:17
great.. will close this one now.
thanks for report

**Closed by maxrd2** 2019-06-12 13:17 UTC
Labels: enhancement, need more info

**Comment by muzena** [comment] 2019-06-14 00:20
> Thanks for the patch, although i'm not sure i will be able to compile it on my system, it has given me a lot of trouble in the past to make it work on Linuxmint so i kindly ask @muzena if he can make a deb version with this patch?
> Or anyone else of course

What patch?

**Comment by duck7000** [comment] 2019-06-14 12:00
@muzena 
I was talking about this patch https://github.com/maxrd2/subtitlecomposer/commit/d919ca0ef4ab1d4708f315ab551a4433088a43ae

But i saw you already made new deb files where all the patches are included that @maxrd2 has made.

Thanks for maintaining the repo!

**Comment by muzena** [comment] 2019-06-14 12:23
@duck7000 
This is auto build, Launchpad scan every 5 hours [Github repo](https://code.launchpad.net/~subtitlecomposer/subtitlecomposer/+git/subtitlecomposer) for a changes, and automatically builds debs in [PPA repo](https://code.launchpad.net/~trebelnik-stefina/+recipe/subtitlecomposer-bionic-disco)

**Comment by duck7000** [comment] 2019-06-14 20:28
Auto build or not i'm glad that this repo exist, and your time to set it up!

Compiling source is with linuxmint 19.1 not a real problem anymore but removing it can be a real problem.
It is so much easier to remove a deb archive.

@maxrd2 do you want/willing to merge the pull request to get this repo at the official releases page?
