### ISSUE TITLE
Problems with line numbering in the waveform after inserting before an existing line

### ISSUE THREAD

**Issue by lunarrunner** [maxrd2/subtitlecomposer#53] opened 2016-04-14 12:05 UTC
An example of the issue:

1. I right click on a line in the list of lines, let's say line 4, and select Insert Before.
1. According to the waveform, now I have two lines that are numbered as line 3, and both of them are highlighted when one of them are selected in the list.

Also, counting of the lines starts at 0 rather than 1 in the waveform.

**Comment by maxrd2** [comment] 2016-04-18 14:18
Issue with two lines having same number is caused by waveform widget not repainting when video is paused.
I think it's duplicate of #46. Will re-check again when that one is fixed.

**Comment by maxrd2** [comment] 2016-04-18 15:19
Should be fixed in commit 31211f6

**Closed by maxrd2** 2016-04-18 15:19 UTC
Labels: bug, duplicate

**Comment by maxrd2** [comment] 2016-05-07 18:58
It should be definitely fixed with commit 5b95491b
